# Setup
title:            'Simon Harman'
tagline:          'Cryptoeconomics'
description:      'Founder and CEO of the Chainflip & Oxen'
url:              https://chainflip.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Simon Harman'
  url:            https://twitter.com/SimonAHarman

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
